name: inception
description: A code editor toolkit for Flutter
version: 0.0.1
homepage: https://github.com/Flutter-Bounty-Hunters/inception

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.4.1
  flutter:
    sdk: flutter
  path: ^1.9.0
  super_editor: ^0.3.0-dev.43
  super_text_layout: ^0.1.19

  # For exporting test tools:
  flutter_test:
    sdk: flutter
  flutter_test_runners: ^0.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  fake_async: ^1.3.3
  flutter_test_goldens: ^0.0.7
  flutter_test_robots: ^0.0.24

flutter:
